### ISSUE TITLE
TEMPLATE.md has link to REACT.md that is showing 404

### ISSUE THREAD

**Issue by ChrisMM** [mjhm/create-react-dapp#1]
/template/TEMPLATE.md has link to https://github.com/mjhm/create-react-dapp/blob/master/template/REACT.md

**Actual**
Clicking the link shows 404

**Expected**
Clicking the link either goes to:
https://github.com/facebook/create-react-app
*or*
https://www.npmjs.com/package/create-react-app

**Comment by mjhm** [comment]
Thanks Chris -- fixed.
